name: Setup Python + Poetry
description: Installs Python and Poetry for AI Forensics workflows
inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
      shell: bash

    - name: Install dependencies
      run: poetry install
      shell: bash
