name: Lint with Black

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  lint:
    name: Black Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Black Format Check
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./ai_forensics"
          version: "25.1.0"
