name: Integrity Check

on:
  push:
    # branches: [main]
    branches: [never]
  pull_request:
    # branches: [main]
    branches: [never]

jobs:
  verify-integrity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integrity

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install cryptography

      - name: Verify manifest and fingerprint
        run: python verifier.py
