name: SonarCloud

on:
  workflow_run:
    # workflows: ["Pytest & Coverage"]
    workflows: ["never"]
    types:
      - completed

jobs:
  sonarcloud:
    name: SonarCloud Scan
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Set up Python
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: '3.10'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # This only works reliably for the default branch.
      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarcloud-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
