# .github/workflows/test-dispatch.yml
name: Manual Test Workflow

on:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Workflow ran successfully!"
