name: Pytest & Coverage

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests and generate coverage
        run: |
          poetry run pytest --cov=ai_forensics --cov-report=xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
