name: Verify Release Bundle

on:
  push:
    tags:
      - 'v*'

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify Cosign + Manifest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Download and unpack release bundle
        uses: actions/download-artifact@v4
        with:
          name: release-bundle
          path: release/

      - name: Verify bundle
        run: |
          poetry run python tools/verify_release.py release/
